[package]
name = "devbridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "devbridge"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
clap.workspace = true
clap_complete.workspace = true
comfy-table.workspace = true
devbridge-core = { path = "../devbridge-core" }
devbridge-tunnel = { path = "../devbridge-tunnel" }
reqwest.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
